// <auto-generated />
using System;
using BuyPizza.Models.dbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuyPizza.Migrations
{
    [DbContext(typeof(pizzaContext))]
    [Migration("20230412203444_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuyPizza.Models.Item", b =>
                {
                    b.Property<long>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemID");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemID = 1L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3669),
                            Description = "Pizza Cake",
                            Image = "PizzaCake.jpg",
                            Name = "Pizza Cake",
                            Rate = 99.0
                        },
                        new
                        {
                            ItemID = 2L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3706),
                            Description = "St. Louis-Style Pizza",
                            Image = "StLouisStylePizza.jpg",
                            Name = "St. Louis-Style Pizza",
                            Rate = 199.0
                        },
                        new
                        {
                            ItemID = 3L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3722),
                            Description = "Pizza ortolana",
                            Image = "Pizzaortolana.jpg",
                            Name = "Pizza ortolana",
                            Rate = 299.0
                        },
                        new
                        {
                            ItemID = 4L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3737),
                            Description = "Pizza alla pala",
                            Image = "Pizzaallapala.jpg",
                            Name = "Pizza alla pala",
                            Rate = 149.0
                        },
                        new
                        {
                            ItemID = 5L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3751),
                            Description = "Pizza pesto Genovese",
                            Image = "PizzapestoGenovese.jpg",
                            Name = "Pizza pesto Genovese",
                            Rate = 249.0
                        },
                        new
                        {
                            ItemID = 6L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3769),
                            Description = "Pizza rustica",
                            Image = "Pizzarustica.jpg",
                            Name = "Pizza rustica",
                            Rate = 349.0
                        },
                        new
                        {
                            ItemID = 7L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3785),
                            Description = "Fugazzeta",
                            Image = "Fugazzeta.jpg",
                            Name = "Fugazzeta",
                            Rate = 399.0
                        },
                        new
                        {
                            ItemID = 8L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3799),
                            Description = "Pizza e fichi",
                            Image = "Pizzaefichi.jpg",
                            Name = "Pizza e fichi",
                            Rate = 449.0
                        },
                        new
                        {
                            ItemID = 9L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3813),
                            Description = "Apizza",
                            Image = "Apizza.jpg",
                            Name = "Apizza",
                            Rate = 229.0
                        },
                        new
                        {
                            ItemID = 10L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3922),
                            Description = "Pugliese Pizza",
                            Image = "PugliesePizza.jpg",
                            Name = "Pugliese Pizza",
                            Rate = 279.0
                        },
                        new
                        {
                            ItemID = 11L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3943),
                            Description = "Tomato Pie",
                            Image = "TomatoPie.jpg",
                            Name = "Tomato Pie",
                            Rate = 489.0
                        });
                });

            modelBuilder.Entity("BuyPizza.Models.ItemTopping", b =>
                {
                    b.Property<long>("ItemToppingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemToppingID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemID")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<long>("ToppingID")
                        .HasColumnType("bigint")
                        .HasColumnName("ToppingID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemToppingID");

                    b.HasIndex("ItemID");

                    b.HasIndex("ToppingID");

                    b.ToTable("ItemTopping");

                    b.HasData(
                        new
                        {
                            ItemToppingID = 1L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4068),
                            ItemID = 1L,
                            ToppingID = 1L
                        },
                        new
                        {
                            ItemToppingID = 2L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4087),
                            ItemID = 1L,
                            ToppingID = 3L
                        },
                        new
                        {
                            ItemToppingID = 3L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4101),
                            ItemID = 2L,
                            ToppingID = 5L
                        },
                        new
                        {
                            ItemToppingID = 4L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4114),
                            ItemID = 2L,
                            ToppingID = 2L
                        },
                        new
                        {
                            ItemToppingID = 5L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4127),
                            ItemID = 3L,
                            ToppingID = 4L
                        },
                        new
                        {
                            ItemToppingID = 6L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4141),
                            ItemID = 3L,
                            ToppingID = 6L
                        },
                        new
                        {
                            ItemToppingID = 7L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4154),
                            ItemID = 4L,
                            ToppingID = 1L
                        },
                        new
                        {
                            ItemToppingID = 8L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4167),
                            ItemID = 4L,
                            ToppingID = 3L
                        },
                        new
                        {
                            ItemToppingID = 9L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4179),
                            ItemID = 5L,
                            ToppingID = 5L
                        },
                        new
                        {
                            ItemToppingID = 10L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4193),
                            ItemID = 5L,
                            ToppingID = 2L
                        },
                        new
                        {
                            ItemToppingID = 11L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4205),
                            ItemID = 6L,
                            ToppingID = 4L
                        },
                        new
                        {
                            ItemToppingID = 12L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4219),
                            ItemID = 6L,
                            ToppingID = 6L
                        },
                        new
                        {
                            ItemToppingID = 13L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4231),
                            ItemID = 7L,
                            ToppingID = 1L
                        },
                        new
                        {
                            ItemToppingID = 14L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4244),
                            ItemID = 7L,
                            ToppingID = 3L
                        },
                        new
                        {
                            ItemToppingID = 15L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4256),
                            ItemID = 7L,
                            ToppingID = 5L
                        },
                        new
                        {
                            ItemToppingID = 16L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4270),
                            ItemID = 8L,
                            ToppingID = 2L
                        },
                        new
                        {
                            ItemToppingID = 17L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4283),
                            ItemID = 8L,
                            ToppingID = 4L
                        },
                        new
                        {
                            ItemToppingID = 18L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4377),
                            ItemID = 9L,
                            ToppingID = 6L
                        },
                        new
                        {
                            ItemToppingID = 19L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4396),
                            ItemID = 9L,
                            ToppingID = 1L
                        },
                        new
                        {
                            ItemToppingID = 20L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4410),
                            ItemID = 9L,
                            ToppingID = 3L
                        },
                        new
                        {
                            ItemToppingID = 21L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4423),
                            ItemID = 10L,
                            ToppingID = 5L
                        },
                        new
                        {
                            ItemToppingID = 22L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4436),
                            ItemID = 10L,
                            ToppingID = 2L
                        },
                        new
                        {
                            ItemToppingID = 23L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4448),
                            ItemID = 11L,
                            ToppingID = 4L
                        },
                        new
                        {
                            ItemToppingID = 24L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4461),
                            ItemID = 11L,
                            ToppingID = 6L
                        },
                        new
                        {
                            ItemToppingID = 25L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4474),
                            ItemID = 11L,
                            ToppingID = 1L
                        },
                        new
                        {
                            ItemToppingID = 26L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4487),
                            ItemID = 11L,
                            ToppingID = 3L
                        },
                        new
                        {
                            ItemToppingID = 27L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4499),
                            ItemID = 8L,
                            ToppingID = 5L
                        },
                        new
                        {
                            ItemToppingID = 28L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4512),
                            ItemID = 9L,
                            ToppingID = 2L
                        },
                        new
                        {
                            ItemToppingID = 29L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4524),
                            ItemID = 8L,
                            ToppingID = 4L
                        },
                        new
                        {
                            ItemToppingID = 30L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4537),
                            ItemID = 7L,
                            ToppingID = 6L
                        });
                });

            modelBuilder.Entity("BuyPizza.Models.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BuyPizza.Models.OrderItem", b =>
                {
                    b.Property<long>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemID")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemID");

                    b.Property<long>("OrderID")
                        .HasColumnType("bigint")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quentity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("BuyPizza.Models.OrderItemTopping", b =>
                {
                    b.Property<long>("OrderItemToppingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemToppingID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderItemID")
                        .HasColumnType("bigint")
                        .HasColumnName("OrderItemID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ToppingID")
                        .HasColumnType("bigint")
                        .HasColumnName("ToppingID");

                    b.HasKey("OrderItemToppingID");

                    b.HasIndex("OrderItemID");

                    b.HasIndex("ToppingID");

                    b.ToTable("OrderItemTopping");
                });

            modelBuilder.Entity("BuyPizza.Models.Topping", b =>
                {
                    b.Property<long>("ToppingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ToppingID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ToppingID");

                    b.ToTable("Topping");

                    b.HasData(
                        new
                        {
                            ToppingID = 1L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3962),
                            Image = "RoastedTomatoes.jpg",
                            Name = "Roasted Tomatoes",
                            Rate = 49.0
                        },
                        new
                        {
                            ToppingID = 2L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(3986),
                            Image = "RoastedRedPeppers.jpg",
                            Name = "Roasted Red Peppers",
                            Rate = 39.0
                        },
                        new
                        {
                            ToppingID = 3L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4002),
                            Image = "RoastedArtichokes.jpg",
                            Name = "Roasted Artichokes",
                            Rate = 59.0
                        },
                        new
                        {
                            ToppingID = 4L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4019),
                            Image = "RoastedButternutSquash.jpg",
                            Name = "Roasted Butternut Squash",
                            Rate = 89.0
                        },
                        new
                        {
                            ToppingID = 5L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4034),
                            Image = "RoastedBroccoli.jpg",
                            Name = "Roasted Broccoli",
                            Rate = 49.0
                        },
                        new
                        {
                            ToppingID = 6L,
                            CreatedDate = new DateTime(2023, 4, 12, 20, 34, 44, 70, DateTimeKind.Utc).AddTicks(4051),
                            Image = "RoastedFennel.jpg",
                            Name = "Roasted Fennel",
                            Rate = 89.0
                        });
                });

            modelBuilder.Entity("BuyPizza.Models.ItemTopping", b =>
                {
                    b.HasOne("BuyPizza.Models.Item", "Item")
                        .WithMany("ItemToppings")
                        .HasForeignKey("ItemID")
                        .IsRequired();

                    b.HasOne("BuyPizza.Models.Topping", "Topping")
                        .WithMany("ItemToppings")
                        .HasForeignKey("ToppingID")
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("BuyPizza.Models.OrderItem", b =>
                {
                    b.HasOne("BuyPizza.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .IsRequired();

                    b.HasOne("BuyPizza.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BuyPizza.Models.OrderItemTopping", b =>
                {
                    b.HasOne("BuyPizza.Models.OrderItem", "OrderItem")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("OrderItemID")
                        .IsRequired();

                    b.HasOne("BuyPizza.Models.Topping", "Topping")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("ToppingID")
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("BuyPizza.Models.Item", b =>
                {
                    b.Navigation("ItemToppings");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BuyPizza.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BuyPizza.Models.OrderItem", b =>
                {
                    b.Navigation("OrderItemToppings");
                });

            modelBuilder.Entity("BuyPizza.Models.Topping", b =>
                {
                    b.Navigation("ItemToppings");

                    b.Navigation("OrderItemToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
